//
//  BlogPosts.swift
//  BlogApp
//
//  Created by MacBook on 17/03/1443 AH.
//


import Foundation
struct BlogPosts :Identifiable {
    
    var id : Int
    var name : String
    var image : String
    var details : String
    var Pimage : String
    var person : String
 
}
var latestpost = [


BlogPosts(id: 0, name: " The Sakura", image: "a5", details: "“Prunus serrulata” is the Japanese term for flowering cherry trees that appear for a short time each spring. These trees are different from other types of cherry fruit trees Their natural beauty has made them a powerful symbol of Japanese art, culture and identity, and some consider cherry blossoms to be the unofficial national flower of Japan. Every year, the Japanese track the blossoming progress of the cherry trees. Or the sakura tree, which grows slowly with hot weather, which begins in Okinawa in January and progresses to Kyoto and Tokyo at the beginning of April. As the cherry trees begin to bloom in every region of Japan, the ritual of the hanami ceremony begins, a tradition of strolling under the cherry tree that blooms constantly to showcase its natural beauty. Hanami is a centuries-old tradition of joy through festivals and celebrations in honor of the beauty of cherry blossoms. Most Japanese schools feature cherry blossom trees. Because the school year begins in April each year, the first day of school often coincides with cherry blossom season. The way they bloom once and die soon afterwards has become a powerful symbol in Japan for humanity as people associate flower death with mortality and how short and precious life can be. Because of the flower's symbolic power and natural beauty, cherry blossoms are often used in Japanese art, as well as in the design of all kinds of consumer goods. Japanese cherry blossoms are seen as good luck and a symbol of love and spring. But Japan is not the only place where you can find beautiful cherry trees. In 1912, Japan gave the United States more than 3,000 cherry trees as gifts to celebrate the friendship of the two nations. The trees were planted in Sakura Park in New York City, as well as along the shore of the Tidal Basin in Washington, D.C., near the Jefferson Memorial site. In the United States, Japanese cherry trees are a popular tourist attraction. Every spring, hundreds of thousands of people enjoy the beauty of the trees' during the annual National Cherry Blossom Festival. Japanese cherry trees can also be found in large numbers in many other American cities, including San Diego, Los Angeles, Philadelphia, and Macon, Georgia. Cherry blossoms are edible. Many Japanese cherry blossoms are preserved in salt and vinegar for use as a flavorful food ingredient.", Pimage: "i5", person: "Amal"),
    
    BlogPosts(id: 1, name: "cats communicate ", image: "a22", details: "Cats use postures and movements to communicate a wide range of information. Some include a wide range of responses such as when cats arch their backs, straighten their hair and adopt a posture to convey fear or aggression. Other cats just have one behavioral change (as humans perceive it) such as walking slowly to indicate relaxation. Domestic cats frequently use visual contact with their eyes, ears, mouths, tails, coat, and body positions. It has been stated that cats' facial features change in particular and may be the best indicator of cat communication.  When cats lie on their backs and the abdomen remains exposed, they are in a vulnerable position. Therefore, this situation may convey a feeling of confidence [citation needed] or comfort. However, cats may also wrap their backs to defend themselves with their claws. When cats are calm, they tend to relax with a steady tail. If they are aggressive, their hind legs are more rigid, the rump is raised but the back remains flat, the tail hair is erect, the nose is pushed forward, and the ears are pulled back a little. Because cats have claws and teeth, they can injure anyone who gets into a fight with them, so this situation is the opponent's attempt to wrest respect without a fight.",Pimage: "i3", person: "Hanan"),
    
    
    BlogPosts(id: 2, name: "Life and Nature", image: "a4", details: "Nature and contemplation of it may inspire us and many benefits that we do not know.... Have you ever wondered how inspired you feel when you lose motivation? Among other tips, to boost inspiration is to connect with nature. Furthermore, staying in touch with nature may affect the way people appreciate the natural environment. Having plants in the workplace or at home helps reduce stress, the healing power of nature goes further. Recovery from illness or surgery is faster and requires fewer pain relievers with hospital scenes. More surprisingly, nature positively influences blood pressure, cholesterol, triglyceride, and cortisol levels.",Pimage: "i4", person: "Sally"),
    
    
    BlogPosts(id: 3, name: "Louvre Museum", image: "a2", details: "The Louvre Museum (French: Musée du Louvre) is one of the most important art museums in the world[5], and is located on the north bank of the Seine in Paris, the capital of France. The Louvre Museum is the largest art gallery in the world and contains many different human civilizations, and in the museum there is the famous painting Mona Lisa by the painter Leonardo da Vinci. The name of the place on which it was built, to turn later into a royal palace known as the Louvre Palace, inhabited by the kings of France, and the last to take it as an official residence was Louis XIV, who left it to Versailles in 1672 to be the seat of the new government, leaving the Louvre to be a headquarters that contains a group of royal antiques and sculptures on the face particular.In 1692, the building was occupied by two academies of acting, sculpture and painting, which opened its first salons in 1699. It has occupied the building for 100 years. During the French Revolution, the National Assembly declared that the Louvre should be a national museum, displaying the masterpieces of the nation. The museum opened on August 10, 1793. The Louvre is the largest national museum in France and the most visited museum in the world.[6] Under the late French President Francois Mitterrand, it underwent major reforms and expansion. The Louvre Museum, the largest in Europe, takes the visitor on a global journey through 460,000 pieces of art, including some world heritage masterpieces such as the Venus de Milo statue, the Mona Lisa, and others.",Pimage: "i2",person: "Arwa"),

BlogPosts(id: 4, name: "The art", image: "a1", details: "Art is an important thing in our lives. Painting art is divided into seven types of art, namely plastic art, abstract art, decorative art, illustration art, graphic art, narrative art, and geometric art. Plastic Art The first type of drawing is plastic art, and in this type the artist chooses a certain idea, then reshapes and formulates it in a new way according to his view and belief towards this idea. This formation and this new formulation come in the form of drawings that embody the idea and make it visible by the eye, so that the artist can convey his idea to others after he has formed it in a way that is easy to understand.  Abstract art This type of art depends on drawing abstract drawings, far from the realistic form of the material drawn, as the abstract artist reduces ideas, so they do not appear in the final form similar to reality. Rather, he embodies the shapes through his artistic imagination in a picture that is very different from its reality, and he forms his image using colors only, without trying to clarify the lines. By researching the meaning of the word “abstract”, we find that abstraction in the artistic sense is to get rid of the connection with reality, and abstract art is divided into three other types of art, namely absolute abstraction, abstraction and cubism, and abstract expression. Decorative art, which is one of the types of painting arts that depends on the proportion and proportion between things and some of them, and considers space, mass, composition, size, line, and color among the factors that affect it greatly. Decorative art appears in the form of natural units such as animals, humans, and plants, or in the form of geometric units, which have been transformed into abstract shapes according to the artist's decorative imagination. There are many types of decorative arts, such as: symmetry or symmetry, vegetal decoration, bifurcation, interlacing, and other types of art. Illustrative art is the art that is concerned with clarifying a particular idea or meaning through drawing. The second type is line drawings, and in this type the emphasis is not on all the details, as is the case with photographs. But the artist highlights the element or idea that he wants to highlight through his drawings, while ignoring any other details that may be inherent in the idea. Examples of line drawings include serial drawings, graphs, charts, paintings, and maps.",Pimage: "i1",person: "Jawaher hassan"),

//BlogPosts(id: 5, name: "Bistek Tagalog", image: "0", details: "A dish made of strips of salted and peppred sirloin beef", Pimage: "a1", person: "mo"),
//
//BlogPosts(id: 6, name: "Bistek Tagalog", image: "0", details: "A dish made of strips of salted and peppred sirloin beef", Pimage: "a1",person: "mo"),

]
 var featuredpost = [
    BlogPosts(id: 0, name: " The Sakura", image: "a5", details: "“Prunus serrulata” is the Japanese term for flowering cherry trees that appear for a short time each spring. These trees are different from other types of cherry fruit trees Their natural beauty has made them a powerful symbol of Japanese art, culture and identity, and some consider cherry blossoms to be the unofficial national flower of Japan. Every year, the Japanese track the blossoming progress of the cherry trees. Or the sakura tree, which grows slowly with hot weather, which begins in Okinawa in January and progresses to Kyoto and Tokyo at the beginning of April. As the cherry trees begin to bloom in every region of Japan, the ritual of the hanami ceremony begins, a tradition of strolling under the cherry tree that blooms constantly to showcase its natural beauty. Hanami is a centuries-old tradition of joy through festivals and celebrations in honor of the beauty of cherry blossoms. Most Japanese schools feature cherry blossom trees. Because the school year begins in April each year, the first day of school often coincides with cherry blossom season. The way they bloom once and die soon afterwards has become a powerful symbol in Japan for humanity as people associate flower death with mortality and how short and precious life can be. Because of the flower's symbolic power and natural beauty, cherry blossoms are often used in Japanese art, as well as in the design of all kinds of consumer goods. Japanese cherry blossoms are seen as good luck and a symbol of love and spring. But Japan is not the only place where you can find beautiful cherry trees. In 1912, Japan gave the United States more than 3,000 cherry trees as gifts to celebrate the friendship of the two nations. The trees were planted in Sakura Park in New York City, as well as along the shore of the Tidal Basin in Washington, D.C., near the Jefferson Memorial site. In the United States, Japanese cherry trees are a popular tourist attraction. Every spring, hundreds of thousands of people enjoy the beauty of the trees' during the annual National Cherry Blossom Festival. Japanese cherry trees can also be found in large numbers in many other American cities, including San Diego, Los Angeles, Philadelphia, and Macon, Georgia. Cherry blossoms are edible. Many Japanese cherry blossoms are preserved in salt and vinegar for use as a flavorful food ingredient.", Pimage: "i5", person: "Amal"),
   
    
    
    BlogPosts(id: 1, name: "cats communicate ", image: "a22", details: "Cats use postures and movements to communicate a wide range of information. Some include a wide range of responses such as when cats arch their backs, straighten their hair and adopt a posture to convey fear or aggression. Other cats just have one behavioral change (as humans perceive it) such as walking slowly to indicate relaxation. Domestic cats frequently use visual contact with their eyes, ears, mouths, tails, coat, and body positions. It has been stated that cats' facial features change in particular and may be the best indicator of cat communication.  When cats lie on their backs and the abdomen remains exposed, they are in a vulnerable position. Therefore, this situation may convey a feeling of confidence [citation needed] or comfort. However, cats may also wrap their backs to defend themselves with their claws. When cats are calm, they tend to relax with a steady tail. If they are aggressive, their hind legs are more rigid, the rump is raised but the back remains flat, the tail hair is erect, the nose is pushed forward, and the ears are pulled back a little. Because cats have claws and teeth, they can injure anyone who gets into a fight with them, so this situation is the opponent's attempt to wrest respect without a fight.",Pimage: "i3", person: "Hanan"),

 ]
