//
//  ViewController.swift
//  AzizBlogApp
//
//  Created by Abdulaziz on 18/03/1443 AH.
//


import UIKit

struct Blog {
    var image   : String
    var caption = "Blog"
    var title   : String
    var desc    : String
    var author  = "Image-1"
    var authorName = "Aziz"
}

class BlogPosts {
    static let posts = [
    
        Blog(image: "mo1", caption: "blog", title: "Liverpool and Man City", desc: "Manchester City and Liverpool don’t really believe in this, as neither one really knows how to back up, as they proved in today’s 2-2 draw. Aside from games when Liverpool have every centerback on the roster looking like the Black Knight, these encounters have been enthralling, along with the tension and drama that are inherent. They’re the soccer version of the Battle of Gondor, with each side throwing everything at the other, including themselves.They put on another classic today, at least in the second half. Because it was only one half that was truly competitive, City will probably feel aggrieved at not winning, though a draw on the road against one of their closest competitors makes it a better result for them than for Liverpool. Especially combined with their win at Chelsea last week, meaning they’ve gotten four points from their two hardest games on the slate.Still, City could have easily put this one away in the first half, whereafter the first 10 minutes they sat on Liverpool’s chest for the next 35 like an older brother doing the typewriter to the younger. Liverpool couldn’t escape their own end, and their usual lethal counter had its wings cut off in the hangar. With Diogo Jota starting ahead of Roberto Firmino in Liverpool’s frontline meant that their three forwards were just butting up against City’s backline with no one dropping off to provide an outlet. But City’s pressing and incision means that every pass against them has to be utterly perfect, and if they aren’t teams lose the ball back to them immediately."),
        
        Blog(image: "S1", caption: "blog", title: "thy name is Ole Gunnar", desc: "While most every Manchester United supporter you know will scream at you about what a sneaky good manager Ole Gunnar Solskjær is, and certainly never in a tone or volume that will make you think they’re trying to convince themselves as much as they are you, the urge for all of us who don’t support them is to let them have their fun. The prevailing theory for those of us on the outside is that the more that feeling of “Ole is underappreciated!” pervades through the fans and the club, the less likely they are to go get an established manager of top teams. Especially with someone like Antonio Conte, serial title winner that he is, floating out there at the moment. There’s always someone floating out there, of course, one that we all know is a borderline lock to take all the talent at Man United — as mishmashed as it might be — and make it genuinely title-worthy. But as long as Ole is there, it feels like United have something of a ceiling on what they can do, and the rest of us can be happy.So as annoying as it is to watch Crisitano Ronaldo score yet another undeserved injury time winner yesterday, and it is infuriating, you can’t help but smile a little inside as it’s likely to keep Solskjær in the job just a little longer. Which seems to be his main skill.Would a draw or loss to Villareal have gotten Solskjær fired? No, not on its own. One or no points through two Champions League games would have raised the temperature though. Especially on the heels of a loss to Aston Villa at home the previous Saturday. While they could argue they deserved a point against Villa, and should have gotten one with a last-minute penalty that Bruno Feranandes sent to a ring of Saturn, they could make no such argument yesterday. Villareal were far superior and should have been up multiple goals before Ronaldo did what he always does (that, and dodge rape accusations, obviously).This is what Solskjær has done for just about three seasons now. He arrived at the perfect time for anyone to arrive, and that’s right after José Mourinho was punted out the door in December of 2018. It’s no wonder that every player then played like an elephant was removed from their shoulders, because it basically was, given the pure misery of Mourinho’s time with United. There was no fear of being bus-tossed in the press immediately after a game, or being benched for funsies, or any of the other bullshit Mourinho would engage in. It’s little wonder that United won eight in a row and 10 of 11 as soon as Ole showed up, but look at the teams they beat in that run: Cardiff, Huddersfield, Bournemouth, Newcastle, Reading, Brighton, Fulham. That’s timing! It also didn’t hurt that he had Bruno Fernandes bestowed upon him a month after taking the job, though he could easily argue he gave the Portuguese the freedom Mourinho never would have. Which would be correct."),
        
        Blog(image: "missi", caption: "blog", title: "Missi", desc: "Last spring, when news of the Super League first started to break, I was pretty dismissive. Heard it all before — that type of leak tended to break on a cycle of every few years or so, and would quickly fade into the background. In reality, it did fade into the background pretty quickly. It just did so a lot more noisily, messily, and hilariously than I or anyone else could have thought. It was a real thing for like a day and a half, not just some backroom talks and emails that others constructed into something that was quickly denied. It lived. A butterfly’s lifespan, but it lived.So as news piles up about FIFA’s push for a biennial World Cup, I have to fight my first inclination to dismiss it as just the usual test-balloon/spouting/deranged ranting from one of the world’s more fucked up and greedy organizations. The enormity of that statement is Jupiter-sized, I’m aware. Because, as we learned last spring, the things we used to deride as harebrained, unworkable, and fantastical can actually become real in a hurry. Especially with enough people, enough money on the table, and enough desire to claim all that money.Not that you need the explainer, but no one is buying FIFA’s stated reasoning for pushing for a World Cup every two years, i.e. catering to the fans. The fans are just fine where they are. This is about money. And possibly sticking it to UEFA, but let’s circle back to that in a bit.The World Cup is worth billions to FIFA. And quite frankly, they’re tired of only getting those billions once every four years. They want them every two years, as well as whatever bounty comes with the even-more giblet-thinking Club World Cup. Money is all FIFA is after. And the thing is, they can get a lot of nations to go along with it, because a lot of them will get twice the number of cracks at getting into the big dance as they have before, and all the money that comes along with those opportunities (especially as the tourney is expanding to 48 teams in 2026, in yet another bit of putting your face in first without thinking). Also more nations would get to host the tournament, and though that’s usually a problem for the governments afterward, all the companies that get to build the stadiums and amenities don’t give a flying fuck about that. Why do you think Saudi Arabia is one of the countries pushing this hardest?"),
    ]
}


